GET http://localhost:3001/

###
GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/669773a68f27c55feb45cf5d

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "Does everything still work ? 2",
    "important": true
}

###
PUT http://localhost:3001/api/notes/669773a68f27c55feb45cf5d
Content-Type: application/json

{
    "content": "Does put requests work ?",
    "important": false
}

###
DELETE http://localhost:3001/api/notes/669773a68f27c55feb45cf5d