GET http://localhost:3001/

###
GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/66980c6346c48fe3fabe3e11

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "hello",
    "important": true,
    "userId": "669fe5cb6414dde66428656b"
}

###
PUT http://localhost:3001/api/notes/66980c6346c48fe3fabe3e11
Content-Type: application/json

{
    "content": "hi",
    "important": false
}

###
DELETE http://localhost:3001/api/notes/669773a68f27c55feb45cf5d

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}